# Setup
title: HNL
tagline: Cheat sheets and notes
url: "https://hlechuga.github.com"
paginate: 1
baseurl: "https://hlechuga.github.com"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Harrold Lechuga
  url: "https://www.linkedin.com/in/harroldlechuga"
  email: harrold.lechuga@gmail.com

# Custom vars
version: 3.0.0
